### ISSUE TITLE
GoalTodo : dateTimeDone = null

### ISSUE THREAD

**Issue by StephaneB1** [ATManagerPRO/heigvd-pro-b-01-api#15]
Isn't dateTimeDone the date the goaltodo is supposed to be done ? 
If yes it can't be null

If no, where is the date of the goaltodo (the day the goalTodo takes place) ?

**Comment by rdemarta** [comment]
dateTimeDone is the date and time when the goalTodo has been done by the user (initially null), whereas dueDate is the day when the task must be completed.
