### ISSUE TITLE
Add intervalLabel and IntervalValue in GET goaltodo/today request

### ISSUE THREAD

**Issue by gollgot** [ATManagerPRO/heigvd-pro-b-01-api#8]

**Comment by StephaneB1** [comment]
+ date of creation of the Goal of the goalTodo pls <3

**Comment by gollgot** [comment]
Done,

created_at => is for goalTodo
created_at_goal => is for goal

https://atmanager.gollgot.app/swagger/#/default/get_users__user_id__goaltodos_today
